[project]
site_name = "ML Wiki"
site_description = "üèõÔ∏è Machine Learning Wiki en Espa√±ol"
site_author = "Daniel Bazo Correa"
site_url = "https://danibcorr.github.io/ml-wiki/"
repo_url = "https://github.com/danibcorr/ml-wiki"
repo_name = "danibcorr/ml-wiki"
copyright = "copyright &copy; 2026 Daniel Bazo Correa"
docs_dir = "docs"
nav = [
    {"Inicio" = "index.md" },
    {"Sistemas Operativos" = [
        "capt_1_operative_systems/topic_1_linux.md"
    ]},
    {"Herramientas" = [
        "capt_2_tools/topic_1_git.md"
    ]},
    {"Programaci√≥n" = [
        {"Python" = [
            "capt_3_programming/capt_3_1_python/topic_1_environments.md",
            "capt_3_programming/capt_3_1_python/topic_2_python.md",
            "capt_3_programming/capt_3_1_python/topic_3_libraries.md",
            "capt_3_programming/capt_3_1_python/topic_4_leetcode.md",
        ]},
        {"Scripting" = [
            "capt_3_programming/capt_3_2_scripting/topic_1_bash.md",
            "capt_3_programming/capt_3_2_scripting/topic_2_makefile.md"
        ]},
        {"Bases de Datos" = [
            "capt_3_programming/capt_3_3_databases/topic_1_fundamentals.md",
            "capt_3_programming/capt_3_3_databases/topic_2_sql.md",
            "capt_3_programming/capt_3_3_databases/topic_3_exercises_sql.md"
        ]},
        {"CUDA" = [
            "capt_3_programming/capt_3_4_cuda/topic_1_cuda.md",
            "capt_3_programming/capt_3_4_cuda/topic_2_exercises_cuda.md"
        ]}
    ]}
]
extra_css = ["css/custom.css"]

[project.theme]
language = "es"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
repo = "fontawesome/brands/github"

[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/in/danibcorr/"

[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.tables]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true